# Generated by Django 5.0.6 on 2024-05-31 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercisename', models.CharField(max_length=100)),
                ('exerciseimage', models.ImageField(upload_to='exerciseimage')),
                ('exercisetype', models.CharField(choices=[('basicyogaroutine', 'basicyogaroutine'), ('intermediateyogaroutine', 'intermediateyogaroutine'), ('advancedyogaroutine', 'advancedyogaroutine'), ('basicyoga', 'basicyoga'), ('intermediateyoga', 'intermediateyoga'), ('advancedyoga', 'advancedyoga'), ('basicmeditation', 'basicmeditation'), ('intermediatemeditation', 'intermediatemeditation'), ('advancedmeditation', 'advancedmeditation'), ('basicrelaxation', 'basicrelaxation'), ('intermediaterelaxation', 'intermediaterelaxation'), ('advancedrelaxation', 'advancedrelaxation')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseexplanation', models.CharField(max_length=10000)),
                ('exercisesteps', models.CharField(max_length=10000)),
                ('exercisevideo', models.URLField(max_length=500)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercises')),
            ],
        ),
    ]
