# Generated by Django 5.0.6 on 2024-05-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='detail',
        ),
    ]
