# Generated by Django 5.0.6 on 2024-06-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseexplanation', models.TextField(max_length=10000)),
                ('exercisesteps', models.TextField(max_length=10000)),
                ('exercisevideo', models.URLField(max_length=500)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercises')),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
