# Generated by Django 5.0.6 on 2024-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_detail_exercisesteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='exerciseexplanation',
            field=models.TextField(max_length=10000),
        ),
    ]
