# Generated by Django 5.0.6 on 2024-06-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_dob_customuser_dob_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
